import csv
import os

def generate_latex_table(targets):
    print("\n% --- AUTOMATED RESULTS TABLE (GENERATED BY PIPELINE) ---")
    print(r"\begin{table}[h]")
    print(r"\centering")
    print(r"\caption{Derived Physical and Thermodynamic Parameters}")
    print(r"\label{tab:results}")
    print(r"\begin{tabular}{l c c c c}")
    print(r"\hline")
    print(r"Target & $T_1$ (K) & $T_2$ (K) & $i$ ($^\circ$) & $q$ ($m_2/m_1$) \\")
    print(r"\hline")

    for target in targets:
        safe = target.replace(" ", "_")
        # Check both Thesis1/Thesis1 and root
        results_file = f"results_{safe}.csv"
        if not os.path.exists(results_file):
            results_file = os.path.join("Thesis1", "Thesis1", f"results_{safe}.csv")

        if os.path.exists(results_file):
            data = {}
            with open(results_file, "r", encoding="utf-8") as f:
                reader = csv.reader(f)
                next(reader) # skip header
                for row in reader:
                    if len(row) >= 3:
                        data[row[1]] = row[2]
            
            t1 = data.get("T1_K", "0")
            t2 = data.get("T2_K", "0")
            incl = data.get("incl_deg", "0")
            q = data.get("q", "0")
            
            print(f"{target} & {float(t1):.0f} & {float(t2):.0f} & {float(incl):.1f} & {float(q):.3f} \\\\")
        else:
            print(fr"{target} & \multicolumn{{4}}{{c}}{{[Pending Optimization]}} \\")

    print("\\hline")
    print("\\end{tabular}")
    print("\\end{table}")

if __name__ == "__main__":
    targets = ["WZ And", "AA And", "AB And", "AD And", "BD And"]
    generate_latex_table(targets)
