"""
================================================================================
SCRIPT 05 — INVERSE PROBLEM & POSTERIOR OPTIMIZATION
================================================================================
Thesis: Thermodynamic Analysis and Modeling of Blackbody Radiation in
        Eclipsing Binary Systems Using Space-Based Photometry

Methodology Step 4.5:
    Solves the astrophysical inverse problem using the emcee affine-invariant 
    MCMC sampler. Maps the joint posterior probability distribution for 
    thermodynamic and geometric parameters. Utilizes MPI orchestration for 
    High-Performance Computing (HPC) distribution of 3D mesh rendering.

Dependencies:
    pip install phoebe emcee numpy matplotlib mpi4py

Inputs:
    benchmark_targets.csv — Pipeline target list.
    bundle_<star>.phoebe  — Initialized models from Script 04.

Outputs:
    bundle_<star>_final.phoebe — Optimized bundles with converged posteriors.
    results_<star>.csv         — Final derived physical parameters with errors.
    plots/phoebe_final_<star>.png — Best-fit model verification.
================================================================================
"""

# ── Standard library imports ──────────────────────────────────────────────────
import csv
import os
import warnings

# ── Third-party scientific library imports ────────────────────────────────────
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import phoebe
import emcee  

# ── MPI HPC ORCHESTRATION ─────────────────────────────────────────────────────
# We distribute the 3D mesh rendering (the computational bottleneck) across 
# multiple logical threads while keeping the MCMC orchestration serial.
try:
    from mpi4py import MPI
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()      # Rank 0: Master Orchestrator, Rank 1+: Worker Nodes
    n_procs = comm.Get_size()   
except ImportError:
    rank = 0
    n_procs = 1

def mprint(*args, **kwargs):
    """Ensures terminal output is only generated by the Master node."""
    if rank == 0:
        print(*args, **kwargs)

if rank == 0:
    mprint(f"\n[HPC] MPI Cluster initialized with {n_procs} processor cores.")
# ─────────────────────────────────────────────────────────────────────────────

warnings.filterwarnings("ignore")
phoebe.logger(clevel="WARNING")

PLOT_DIR = "plots"
os.makedirs(PLOT_DIR, exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1: CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────

# [EXPERT FIX] Corrected input file to match the output of previous pipeline stages.
INPUT_CATALOG   = "neglected_targets.csv"
SOLVER_STRATEGY = "emcee"  

# MCMC parameters (Production run settings)
MCMC_NWALKERS = 14         
MCMC_NITER    = 2700       
MCMC_BURNIN   = 400        

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2: FREE PARAMETER DEFINITIONS
# ─────────────────────────────────────────────────────────────────────────────

# For EW (contact) systems
# [EXPERT FIX] The mass ratio (q) is notoriously degenerate with inclination and 
# fillout factor in single-band photometry. It is explicitly kept FIXED at the 
# Nelder-Mead derived value. Thesis documentation must note this physical assumption.
FREE_PARAMETERS_CONTACT = {
    "teff@secondary":      (3000, 10000, "Secondary effective temperature (K)"),
    "incl@binary":         (50.0,  90.0, "Orbital inclination (degrees)"),
    # [EXPERT FIX] Tightened fillout_factor limit from 0.95 to 0.70 to prevent 
    # mesh collapse in highly distorted contact systems.
    "fillout_factor@contact_envelope": (0.0, 0.70, "Fillout factor f"), 
}

# For EB (detached/semi-detached) systems
# [HARDENING] Radii capped at 1.0 and Inclination floor at 60.0 to prevent ghost-star collapse
FREE_PARAMETERS_DETACHED = {
    "teff@secondary":    (3000,  10000, "Secondary effective temperature (K)"),
    "incl@binary":       (60.0,   90.0, "Orbital inclination (degrees)"),
    "q@binary":          ( 0.1,    1.0, "Mass ratio m2/m1"),
    "requiv@primary":    ( 0.1,    1.0, "Equivalent radius R1"),
    "requiv@secondary":  ( 0.1,    1.0, "Equivalent radius R2"),
}

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3: HELPER FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────

def compute_chi2(b, free_params, dataset="lc01"):
    """Computes the strict reduced chi-squared statistic (χ²_red).
       [EXPERT FIX] Removed post-hoc flux scaling. The metric now mathematically 
       reflects the exact residuals the solver is minimizing."""
    try:
        obs_flux  = b.get_value("fluxes", dataset=dataset, context="dataset")
        obs_sigma = b.get_value("sigmas", dataset=dataset, context="dataset")
        syn_flux  = b.get_value("fluxes", dataset=dataset, model="solution_model")

        n_obs     = len(obs_flux)
        n_free    = len(free_params)
        dof       = max(1, n_obs - n_free)
        chi2      = np.sum(((obs_flux - syn_flux) / obs_sigma) ** 2)
        return chi2, (chi2 / dof), n_obs
    except Exception:
        return np.inf, np.inf, 0

def check_convergence(chains):
    """[EXPERT FIX] Replaced Gelman-Rubin with Integrated Autocorrelation Time (τ).
       emcee walkers are inherently correlated. To prove convergence, the chain 
       length (N) must be strictly greater than 50 * τ."""
    try:
        # Calculate tau, tolerating chains that haven't fully reached 50x length yet
        tau = emcee.autocorr.integrated_time(chains, tol=0)
        return tau
    except Exception as e:
        return np.inf

def extract_results(b, free_params):
    """Extracts finalized optimized parameters from the bundle for reporting."""
    results = {}
    
    # [EXPERT FIX] Explicitly specify context='component' to avoid ambiguity 
    # with distributions, priors, or solver parameters.
    T1 = b.get_value("teff", component="primary", context="component")
    T2 = b.get_value("teff", component="secondary", context="component")

    results["T1_K"]       = (T1,      0.0)
    results["T2_K"]       = (T2,      np.nan)
    results["T2_over_T1"] = (T2 / T1, np.nan)
    
    # incl and q are at the binary/orbit level, but we specify context='component' 
    # as PHOEBE places orbit parameters in that hierarchy.
    results["incl_deg"]   = (b.get_value("incl", component="binary", context="component"),  np.nan)
    results["q"]          = (b.get_value("q", component="binary", context="component"),     np.nan)

    if "fillout_factor@contact_envelope" in free_params:
        try:
            # fillout factor is unique to the contact envelope feature
            results["fillout_factor"] = (b.get_value("fillout_factor", context="component"), np.nan)
        except Exception:
            results["fillout_factor"] = (np.nan, np.nan)
    else:
        try:
            results["requiv_primary"]   = (b.get_value("requiv", component="primary", context="component"),   np.nan)
            results["requiv_secondary"] = (b.get_value("requiv", component="secondary", context="component"), np.nan)
        except Exception:
            results["requiv_primary"]   = (np.nan, np.nan)
            results["requiv_secondary"] = (np.nan, np.nan)

    return results

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4: MAIN OPTIMIZATION LOOP
# ─────────────────────────────────────────────────────────────────────────────

targets = []
try:
    with open(INPUT_CATALOG, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            targets.append({
                "name":   row["name"],
                "type":   row["type"],
                "period": float(row["period"]),
            })
except FileNotFoundError:
    mprint(f"ERROR: {INPUT_CATALOG} not found.")
    exit()

# Filter for the remaining production run
targets = [t for t in targets if t["name"] in ["WZ And", "AB And", "BD And"]]

for target in targets:
    name  = target["name"]
    ctype = target["type"]
    safe  = name.replace(" ", "_")

    mprint("\n" + "=" * 70)
    mprint(f"OPTIMIZATION: {name}  ({ctype})  |  Strategy: {SOLVER_STRATEGY.upper()}")
    mprint("=" * 70)

    # Use relative path for WSL compatibility
    bundle_file = f"bundle_{safe}.phoebe"
    if not os.path.exists(bundle_file):
        mprint(f"  WARNING: {bundle_file} not found. Skipping.")
        continue

    b = phoebe.load(bundle_file)
    mprint(f"  Bundle loaded: {bundle_file}")

    # [IMPROVEMENT] Dynamic Radiative Switch (von Zeipel vs Lucy)
    # Ensures the MCMC starts with physically consistent bolometric constants
    for component in ['primary', 'secondary']:
        teff = b.get_value(f'teff@{component}')
        if teff >= 8000:
            b.set_value(f'gravb_bol@{component}', 1.0)
            b.set_value(f'irrad_frac_refl_bol@{component}', 1.0)
            mprint(f"  [PHYSICS] {component.capitalize()} is Radiative ({teff:.0f}K). Setting β1=1.0, A=1.0")
        else:
            b.set_value(f'gravb_bol@{component}', 0.32)
            b.set_value(f'irrad_frac_refl_bol@{component}', 0.6)
            mprint(f"  [PHYSICS] {component.capitalize()} is Convective ({teff:.0f}K). Setting β1=0.32, A=0.6")

    # ── HOTFIX 1: INTERPOLATION DEDUPLICATION ────────────────────────────────
    try:
        times  = b.get_value('times', dataset='lc01', context='dataset')
        fluxes = b.get_value('fluxes', dataset='lc01', context='dataset')
        sigmas = b.get_value('sigmas', dataset='lc01', context='dataset')
        
        # Capture critical parameters before removal
        pb = b.get_value('passband', dataset='lc01', context='dataset')
        pblum_mode = b.get_value('pblum_mode', dataset='lc01')

        unique_times, unique_indices = np.unique(times, return_index=True)

        b.remove_dataset('lc01')
        b.add_dataset('lc', 
                      times=times[unique_indices], 
                      fluxes=fluxes[unique_indices], 
                      sigmas=sigmas[unique_indices], 
                      passband=pb, 
                      dataset='lc01')
        
        # Restore critical configurations
        b.set_value('pblum_mode', dataset='lc01', value=pblum_mode)
        
        removed = len(times) - len(unique_times)
        mprint(f"  [FIX] Data Sanitization: Sorted times and removed {removed} duplicate points.")
    except Exception as e:
        mprint(f"  [FIX WARNING] Could not sanitize dataset: {e}")
    # ─────────────────────────────────────────────────────────────────────────

    # ── HOTFIX 2: PHYSICAL BLACKBODY LIMB DARKENING ──────────────────────────
    # [EXPERT FIX] A mathematically perfect blackbody is NOT a uniform disk. 
    # The Eddington-Barbier relation dictates that stellar limbs appear cooler. 
    # Forcing a 0.0 coefficient artificially darkens the center, biasing R and i.
    # We apply u ≈ 0.6 as a standard solar-type proxy for the TESS passband.
    b.set_value("ld_mode_bol@primary", "manual")
    b.set_value("ld_mode_bol@secondary", "manual")
    
    for comp in ['primary', 'secondary']:
        try:
            b.set_value(f"ld_mode@{comp}@lc01", "manual")
            b.set_value(f"ld_func@{comp}@lc01", "linear")
            b.set_value(f"ld_coeffs@{comp}@lc01", [0.6]) # Physical TESS proxy
        except Exception as e:
            mprint(f"  [LD WARNING] Could not override coefficients for {comp}: {e}")
    # ─────────────────────────────────────────────────────────────────────────

    is_contact = (ctype == "EW")

    if is_contact:
        try:
            b.flip_constraint('fillout_factor', solve_for='pot')
        except Exception:
            pass # Constraint may already be flipped

    free_params = FREE_PARAMETERS_CONTACT if is_contact else FREE_PARAMETERS_DETACHED
    n_free      = len(free_params)

    # ── 4A: APPLY LIMITS & PRIORS ────────────────────────────────────────────

    mprint(f"\n  [4A] Parameter Bounds & Probabilistic Priors ({n_free} free parameters)...")

    if is_contact:
        # [EXPERT FIX] W-Type allowance. W UMa W-type systems have hotter secondaries.
        T1_current = b.get_value("teff@primary", context="component")
        T2_lo, T2_hi = (0.80 * T1_current), (1.25 * T1_current)
        free_params = dict(free_params) 
        free_params["teff@secondary"] = (T2_lo, T2_hi, "Secondary Teff (Thermal Floor Prior)")
        mprint(f"  [HARDENING] Thermal floor enforced: T₂ ∈ [{T2_lo:.0f}, {T2_hi:.0f}] K")
    else:
        # For detached systems, also prevent secondary from being unphysically cold
        T1_current = b.get_value("teff@primary", context="component")
        T2_lo, T2_hi = (0.70 * T1_current), (1.10 * T1_current)
        free_params = dict(free_params) 
        free_params["teff@secondary"] = (T2_lo, T2_hi, "Secondary Teff (Thermal Floor Prior)")
        mprint(f"  [HARDENING] Thermal floor enforced: T₂ ∈ [{T2_lo:.0f}, {T2_hi:.0f}] K")

    if SOLVER_STRATEGY == "emcee":
        prior_dict = {}
        init_dict = {}
        for twig, (lo, hi, desc) in free_params.items():
            prior_dict[twig] = phoebe.uniform(lo, hi)
            
            # [HARDENING] Reduced Gaussian ball to 2% to prevent early Roche overflow
            current_val = b.get_value(twig)
            param_range = hi - lo
            sigma = 0.02 * param_range 
            
            # Ensure the initialization ball is strictly bounded
            init_val = np.clip(current_val, lo + sigma, hi - sigma)
            init_dict[twig] = phoebe.normal(init_val, sigma)
            
            mprint(f"    Added Prior: {twig:<30} [{lo:.2f}, {hi:.2f}]")
        
        b.add_distribution(prior_dict, distribution="my_priors")
        b.add_distribution(init_dict, distribution="my_init")
    else:
        for twig, (lo, hi, desc) in free_params.items():
            b.get_parameter(twig).set_limits((lo, hi))
            mprint(f"    Applied Hard Limit: {twig:<30} [{lo:.2f}, {hi:.2f}]")

    # ── 4B: CONFIGURE SOLVER ──────────────────────────────────────────────────

    mprint(f"\n  [4B] Configuring solver: {SOLVER_STRATEGY}...")

    if SOLVER_STRATEGY == "emcee":
        b.add_solver(
            "sampler.emcee",
            solver="mcmc_sampler",
            init_from="my_init",
            priors="my_priors",
            nwalkers=MCMC_NWALKERS,
            niters=MCMC_NITER,
            overwrite=True
        )
        mprint(f"  MCMC Topology Map: {MCMC_NWALKERS} walkers, {MCMC_NITER} steps.")

    # ── 4C: EXECUTION ─────────────────────────────────────────────────────────

    solver_label = "mcmc_sampler" if SOLVER_STRATEGY == "emcee" else "main_optimizer"

    try:
        mprint(f"\n  [4C] Executing solver. PHOEBE MPI pool will accelerate run_compute...")
        b.run_solver(solver_label, solution="best_solution", overwrite=True)
        mprint("  Solver completed successfully.")
    except Exception as e:
        mprint(f"  Solver error: {e}")
        continue

    # ── 4D: AUTOCORRELATION CONVERGENCE DIAGNOSTICS ───────────────────────────

    if SOLVER_STRATEGY == "emcee":
        mprint("\n  [4D] Checking Posterior Convergence (Autocorrelation Time τ)...")
        try:
            raw_chains = b.get_value("samples", solution="best_solution")
            
            # Reshape chains for emcee format: (nwalkers, nsteps, ndim)
            if raw_chains.ndim != 3:
                n_total  = raw_chains.shape[0]
                n_steps_ = n_total // MCMC_NWALKERS
                raw_chains = raw_chains.reshape(MCMC_NWALKERS, n_steps_, n_free)

            # Swap axes to match emcee.autocorr expected format: (nsteps, nwalkers, ndim)
            chains_swapped = np.swapaxes(raw_chains, 0, 1)
            
            taus = check_convergence(chains_swapped)
            
            mprint(f"  {'Parameter':<35} {'τ (steps)':>12}  {'Status (N > 50τ)'}")
            mprint(f"  {'─'*70}")
            for i, pname in enumerate(list(free_params.keys())):
                tau_val = taus[i] if isinstance(taus, np.ndarray) else np.inf
                status = "✓ Converged" if (MCMC_NITER > 50 * tau_val) else "⚠ Under-converged"
                mprint(f"  {pname:<35} {tau_val:>12.1f}  {status}")
        except Exception as e:
            mprint(f"  Convergence diagnostic failed: {e}")

    # ── 4E/F: ADOPTION & FINAL COMPUTATION ────────────────────────────────────

    mprint("\n  [4E] Adopting best-fit posterior median into physical mesh...")
    try:
        if SOLVER_STRATEGY == "emcee":
            b.adopt_solution("best_solution", burnin=MCMC_BURNIN, adopt_values=True, adopt_distributions=True)
        else:
            b.adopt_solution("best_solution", adopt_values=True)
    except Exception as e:
        mprint(f"  Adoption error: {e}")

    try:
        # [EXPERT FIX] Enabled Wilson irradiation for EW systems. Contact binaries 
        # exchange massive radiative energy which drastically alters out-of-eclipse flux.
        irrad = "wilson" if is_contact else "horvat"
        b.run_compute(model="solution_model", overwrite=True, irrad_method=irrad, distortion_method="roche")
    except Exception as e:
        mprint(f"  Final compute error: {e}")
        continue

    chi2, chi2_red, n_obs = compute_chi2(b, free_params, dataset="lc01")
    mprint(f"\n  Final Reduced χ² = {chi2_red:.4f}  (N = {n_obs}, Degrees of Freedom = {n_obs - n_free})")

    # [IMPROVEMENT] MCMC Convergence Diagnostics (Gelman-Rubin R-hat)
    try:
        # We estimate R-hat by splitting the chain in half
        # and calculating the variance ratio
        chains = b.get_value('samples', solution='best_solution')
        n_walkers, n_steps, n_params = chains.shape
        
        mprint("\n  [CONVERGENCE] Gelman-Rubin Diagnostics (R-hat):")
        fitted_params = b.get_value('fitted_twigs', solution='best_solution')
        
        for i, param in enumerate(fitted_params):
            param_chain = chains[:, :, i]
            # Variance between walkers vs variance within walkers
            W = np.mean(np.var(param_chain, axis=1))
            B = n_steps * np.var(np.mean(param_chain, axis=1))
            var_plus = (1 - 1/n_steps) * W + (1/n_steps) * B
            r_hat = np.sqrt(var_plus / W)
            status = "CONVERGED" if r_hat < 1.1 else "UNCONVERGED"
            mprint(f"    {param:35s} : R-hat = {r_hat:.4f} [{status}]")
    except Exception as e:
        mprint(f"  Gelman-Rubin diagnostic error: {e}")

    # ── 4G/H: MPI MASTER DATA EXPORT & PLOTTING ───────────────────────────────

    results = extract_results(b, free_params)

    PARAM_LABELS = {
        "T1_K":             ("Primary temperature T₁",   "K"),
        "T2_K":             ("Secondary temperature T₂", "K"),
        "T2_over_T1":       ("Temperature ratio T₂/T₁",  "—"),
        "incl_deg":         ("Orbital inclination i",     "°"),
        "q":                ("Mass ratio q = m₂/m₁",     "—"),
        "requiv_primary":   ("Primary Radius R₁",         "—"),
        "requiv_secondary": ("Secondary Radius R₂",       "—"),
        "fillout_factor":   ("Contact fillout factor f",  "—"),
    }

    mprint("\n  ─── FINAL PARAMETER POSTERIOR ─────────────────────────────")
    for key, (val, err) in results.items():
        if np.isfinite(val):
            label, unit = PARAM_LABELS.get(key, (key, ""))
            mprint(f"  {label:<30} {val:>10.4f}  {unit}")

    # Ensure ONLY the Master Node writes to the disk to prevent file corruption
    if rank == 0:
        result_file = f"results_{safe}.csv"
        with open(result_file, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["Parameter", "Symbol", "Value", "Unit"])
            for key, (val, err) in results.items():
                label, unit = PARAM_LABELS.get(key, (key, ""))
                writer.writerow([label, key, val, unit])
            writer.writerow(["Reduced chi-squared", "chi2_red", chi2_red, "—"])
            writer.writerow(["Solver strategy", "solver", SOLVER_STRATEGY, "—"])

        try:
            obs_flux  = b.get_value("fluxes", dataset="lc01", context="dataset")
            obs_times = b.get_value("times",  dataset="lc01", context="dataset")
            obs_sigma = b.get_value("sigmas", dataset="lc01", context="dataset")
            syn_flux  = b.get_value("fluxes", dataset="lc01", model="solution_model")
            syn_times = b.get_value("times",  dataset="lc01", model="solution_model")

            # Normalization removed here to ensure plot matches solver output
            P_final  = b.get_value("period@binary")
            T0_final = b.get_value("t0_supconj@binary")

            obs_phase = ((obs_times - T0_final) / P_final + 0.5) % 1.0 - 0.5
            syn_phase = ((syn_times - T0_final) / P_final + 0.5) % 1.0 - 0.5
            sort_idx  = np.argsort(syn_phase)

            residuals = obs_flux - np.interp(obs_phase, syn_phase[sort_idx], syn_flux[sort_idx])

            fig, axes = plt.subplots(2, 1, figsize=(10, 7), gridspec_kw={"height_ratios": [3, 1]})
            fig.suptitle(f"{name} — MCMC Optimized Fit (χ²_red = {chi2_red:.2f})", fontsize=14, fontweight='bold')

            axes[0].errorbar(obs_phase, obs_flux, yerr=obs_sigma, fmt="k.", ms=6, alpha=0.5, label="TESS Observations")
            axes[0].plot(syn_phase[sort_idx], syn_flux[sort_idx], "r-", lw=2.5, label=f"Optimized Model")
            
            param_text = f"T₁ = {results['T1_K'][0]:.0f} K  |  T₂ = {results.get('T2_K', (np.nan,))[0]:.0f} K  |  i = {results['incl_deg'][0]:.1f}°"
            axes[0].text(0.02, 0.04, param_text, transform=axes[0].transAxes, fontsize=10, bbox=dict(boxstyle="round,pad=0.4", fc="lightyellow", alpha=0.9))
                         
            axes[0].set_ylabel("Normalized Flux")
            axes[0].legend(loc="upper right")
            axes[0].grid(alpha=0.3)

            axes[1].plot(obs_phase, residuals, ".", ms=5, color="steelblue", alpha=0.7)
            axes[1].axhline(0.0, color="r", lw=1.5, ls="--")
            axes[1].set_xlabel("Orbital Phase φ")
            axes[1].set_ylabel("Residuals")
            axes[1].grid(alpha=0.3)

            plt.tight_layout()
            plt.savefig(os.path.join(PLOT_DIR, f"phoebe_final_{safe}.png"), dpi=150, bbox_inches="tight")
            plt.close()
            
            b.save(f"bundle_{safe}_final.phoebe")
        except Exception as e:
            mprint(f"  Could not generate final plot/bundle: {e}")

mprint("\n" + "=" * 70)
mprint("SCRIPT 05 COMPLETE — Statistical optimization finished.")
mprint("=" * 70)